#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Tim Dime
url: 'https://timdime.com'
baseurl: '/' #change it according to your repository name
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: green # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
